version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  phoenix:
    build: .
    ports:
      - 4000:4000
    links:
      - db
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db:5432/postgres
